crazyflies:
- channel: 125
  id: 193
  initialPosition:
  - 0
  - 0
  - 0
  type: default
- channel: 125
  id: 194
  initialPosition:
  - 2
  - 0.0
  - 0.0
  type: default
- channel: 125
  id: 195
  initialPosition:
  - 0
  - 2
  - 0.0
  type: default

- channel: 125
  id: 196
  initialPosition:
  - 2
  - 2
  - 0
  type: default
